ROUTINES = [
    {
        "id": "diario",
        "title": "Diario",
        "frequency": "Completar todos los días",
        "description": "Rutina base para evitar acumulación de platos, polvo, basura, ropa y objetos fuera de lugar.",
        "sort_order": 1,
        "tasks": [
            ("diario-1", "Tender camas", "Dormitorios"),
            ("diario-2", "Ventilar habitaciones 10–15 minutos", "Toda la casa"),
            ("diario-3", "Lavar platos o cargar lavavajillas", "Cocina"),
            ("diario-4", "Limpiar mesada, cocina y mesa después de comer", "Cocina / comedor"),
            ("diario-5", "Barrer zonas de mayor tránsito", "Sala / cocina / pasillos"),
            ("diario-6", "Sacar basura si está llena o tiene olor", "Cocina / baños"),
            ("diario-7", "Guardar ropa, calzados y objetos fuera de lugar", "Toda la casa"),
            ("diario-8", "Limpiar derrames o manchas recientes", "Toda la casa"),
            ("diario-9", "Revisar comida vencida o restos visibles", "Cocina / heladera"),
            ("diario-10", "Dejar pileta y lavamanos sin residuos", "Cocina / baños"),
            ("diario-11", "Pasar paño rápido en superficies de alto uso", "Mesas / controles / picaportes"),
            ("diario-12", "Preparar la casa para el día siguiente", "Entrada / sala / cocina"),
        ],
    },
    {
        "id": "cada-3-dias",
        "title": "Cada 3 días",
        "frequency": "2 a 3 veces por semana",
        "description": "Rutina intermedia para mantener baños, pisos, ropa y superficies bajo control sin esperar al fin de semana.",
        "sort_order": 2,
        "tasks": [
            ("cada-3-dias-1", "Trapear pisos principales", "Sala / cocina / pasillos"),
            ("cada-3-dias-2", "Limpiar baño de uso frecuente", "Baños"),
            ("cada-3-dias-3", "Cambiar toallas de mano", "Baños / cocina"),
            ("cada-3-dias-4", "Limpiar espejos con marcas visibles", "Baños / dormitorios"),
            ("cada-3-dias-5", "Pasar paño húmedo en muebles visibles", "Sala / dormitorios"),
            ("cada-3-dias-6", "Ordenar escritorio o mesa principal", "Oficina / sala"),
            ("cada-3-dias-7", "Lavar ropa acumulada", "Lavadero"),
            ("cada-3-dias-8", "Doblar y guardar ropa limpia", "Dormitorios"),
            ("cada-3-dias-9", "Regar plantas según necesidad", "Interior / exterior"),
            ("cada-3-dias-10", "Revisar basureros secundarios", "Baños / oficina / dormitorios"),
            ("cada-3-dias-11", "Limpiar zona de mascotas si corresponde", "Patio / interior"),
            ("cada-3-dias-12", "Reponer papel higiénico, jabón y bolsas", "Baños / cocina"),
        ],
    },
    {
        "id": "semanal",
        "title": "Semanal",
        "frequency": "1 vez por semana",
        "description": "Bloque principal de limpieza profunda ligera. Ideal para asignar un día fijo por semana.",
        "sort_order": 3,
        "tasks": [
            ("semanal-1", "Cambiar y lavar sábanas", "Dormitorios"),
            ("semanal-2", "Lavar fundas de almohadas", "Dormitorios"),
            ("semanal-3", "Aspirar o barrer bajo camas y sillones", "Dormitorios / sala"),
            ("semanal-4", "Limpiar polvo de muebles, estantes y repisas", "Toda la casa"),
            ("semanal-5", "Limpiar baño completo: inodoro, ducha, lavamanos y griferías", "Baños"),
            ("semanal-6", "Limpiar cocina completa: horno, hornallas, campana y azulejos cercanos", "Cocina"),
            ("semanal-7", "Limpiar microondas", "Cocina"),
            ("semanal-8", "Limpiar puertas de heladera y electrodomésticos", "Cocina"),
            ("semanal-9", "Organizar heladera y tirar alimentos vencidos", "Cocina"),
            ("semanal-10", "Cambiar repasadores y trapos de cocina", "Cocina"),
            ("semanal-11", "Limpiar superficies de alto contacto si hubo enfermedad", "Picaportes / interruptores / controles"),
            ("semanal-12", "Lavar basureros pequeños", "Cocina / baños"),
            ("semanal-13", "Ordenar placares superficiales", "Dormitorios"),
            ("semanal-14", "Limpiar entrada, felpudo y zona de calzados", "Entrada"),
            ("semanal-15", "Revisar stock de productos de limpieza", "Lavadero"),
        ],
    },
    {
        "id": "quincenal",
        "title": "Quincenal",
        "frequency": "Cada 15 días",
        "description": "Control de acumulaciones: vidrios, alacena, colchones, zócalos, artículos vencidos y tecnología.",
        "sort_order": 4,
        "tasks": [
            ("quincenal-1", "Limpiar vidrios interiores", "Ventanas"),
            ("quincenal-2", "Limpiar ventiladores o filtros visibles de aire acondicionado", "Dormitorios / sala"),
            ("quincenal-3", "Ordenar alacena", "Cocina"),
            ("quincenal-4", "Limpiar interior de muebles de baño", "Baños"),
            ("quincenal-5", "Aspirar colchones", "Dormitorios"),
            ("quincenal-6", "Lavar cubrecamas livianos o mantas de uso frecuente", "Dormitorios / sala"),
            ("quincenal-7", "Limpiar zócalos visibles", "Toda la casa"),
            ("quincenal-8", "Limpiar controles remotos, teclados y mouse", "Sala / oficina"),
            ("quincenal-9", "Revisar medicamentos vencidos", "Botiquín"),
            ("quincenal-10", "Revisar productos duplicados o innecesarios", "Baño / cocina / lavadero"),
            ("quincenal-11", "Limpiar rejillas y desagües visibles", "Cocina / baños"),
            ("quincenal-12", "Ordenar cables, cargadores y pequeños electrónicos", "Oficina / sala"),
        ],
    },
    {
        "id": "mensual",
        "title": "Mensual",
        "frequency": "1 vez por mes",
        "description": "Mantenimiento mensual para electrodomésticos, humedad, documentos, zonas altas y limpieza profunda puntual.",
        "sort_order": 5,
        "tasks": [
            ("mensual-1", "Limpiar ventanas por dentro y por fuera si es posible", "Toda la casa"),
            ("mensual-2", "Limpiar o aspirar cortinas livianas", "Dormitorios / sala"),
            ("mensual-3", "Limpiar profundamente heladera", "Cocina"),
            ("mensual-4", "Limpiar horno a fondo", "Cocina"),
            ("mensual-5", "Limpiar campana / extractor y filtro", "Cocina"),
            ("mensual-6", "Limpiar lavarropas: goma, filtro y tambor", "Lavadero"),
            ("mensual-7", "Limpiar desagües con método seguro", "Cocina / baños"),
            ("mensual-8", "Lavar basureros grandes", "Cocina / patio"),
            ("mensual-9", "Revisar humedad, moho o filtraciones", "Baños / paredes / techo"),
            ("mensual-10", "Ordenar documentos, facturas y papeles", "Oficina"),
            ("mensual-11", "Donar o descartar objetos sin uso", "Toda la casa"),
            ("mensual-12", "Revisar focos, alargues, enchufes y zapatillas eléctricas", "Toda la casa"),
            ("mensual-13", "Limpiar muebles altos y parte superior de placares", "Cocina / dormitorios"),
        ],
    },
    {
        "id": "cada-3-meses",
        "title": "Cada 3 meses",
        "frequency": "Cada 3 meses",
        "description": "Rutina trimestral para zonas ocultas, plagas, depósitos, tapizados, alacena y mantenimiento preventivo.",
        "sort_order": 6,
        "tasks": [
            ("cada-3-meses-1", "Lavar almohadas o enviarlas a lavar si aplica", "Dormitorios"),
            ("cada-3-meses-2", "Rotar colchón si el fabricante lo permite", "Dormitorios"),
            ("cada-3-meses-3", "Limpiar detrás de heladera, cocina y muebles pesados", "Cocina / sala"),
            ("cada-3-meses-4", "Revisar y limpiar canaletas si hay acceso seguro", "Exterior"),
            ("cada-3-meses-5", "Fumigar o controlar plagas preventivamente", "Interior / exterior"),
            ("cada-3-meses-6", "Ordenar placares completos", "Dormitorios"),
            ("cada-3-meses-7", "Revisar herramientas, cables y artículos guardados", "Depósito / garaje"),
            ("cada-3-meses-8", "Limpiar profundamente sofás y tapizados", "Sala"),
            ("cada-3-meses-9", "Revisar vencimiento de alimentos secos", "Alacena"),
            ("cada-3-meses-10", "Limpiar tanque de agua si corresponde al mantenimiento local", "Exterior"),
            ("cada-3-meses-11", "Revisar siliconas / sellos en baño y cocina", "Baños / cocina"),
            ("cada-3-meses-12", "Ordenar decoración y objetos acumulados", "Toda la casa"),
        ],
    },
    {
        "id": "cada-6-meses",
        "title": "Cada 6 meses",
        "frequency": "2 veces por año",
        "description": "Limpieza semestral pesada y revisión general de seguridad, instalaciones, cortinas, alfombras y depósito.",
        "sort_order": 7,
        "tasks": [
            ("cada-6-meses-1", "Limpieza profunda general", "Toda la casa"),
            ("cada-6-meses-2", "Lavar cortinas pesadas", "Sala / dormitorios"),
            ("cada-6-meses-3", "Limpiar alfombras profundamente", "Sala / dormitorios"),
            ("cada-6-meses-4", "Revisar estado de pintura, humedad y grietas", "Paredes / techo"),
            ("cada-6-meses-5", "Revisar sellos de ventanas y puertas", "Toda la casa"),
            ("cada-6-meses-6", "Revisar extintor si hay", "Cocina / garaje"),
            ("cada-6-meses-7", "Revisión visual del sistema eléctrico básico", "Tablero / tomas"),
            ("cada-6-meses-8", "Limpiar depósito, garaje o quincho", "Exterior"),
            ("cada-6-meses-9", "Revisar filtros de aire acondicionado con técnico si corresponde", "Equipos AC"),
            ("cada-6-meses-10", "Descarte general de ropa, objetos y cajas acumuladas", "Toda la casa"),
            ("cada-6-meses-11", "Revisar botiquín y elementos de emergencia", "Botiquín / depósito"),
            ("cada-6-meses-12", "Actualizar inventario de limpieza y mantenimiento", "Lavadero"),
        ],
    },
    {
        "id": "anual",
        "title": "Anual",
        "frequency": "1 vez por año",
        "description": "Checklist anual de mantenimiento preventivo de la vivienda, equipos, seguridad y limpieza profunda.",
        "sort_order": 8,
        "tasks": [
            ("anual-1", "Mantenimiento profesional de aire acondicionado", "Toda la casa"),
            ("anual-2", "Revisión eléctrica preventiva si la instalación es antigua", "Tablero / circuitos"),
            ("anual-3", "Limpieza profunda de tanque de agua", "Exterior"),
            ("anual-4", "Revisión de techo, goteras y canaletas", "Exterior"),
            ("anual-5", "Revisión de termotanque / calefón", "Baño / lavadero"),
            ("anual-6", "Limpieza profunda de muebles de cocina por dentro", "Cocina"),
            ("anual-7", "Inventario general de herramientas y repuestos", "Depósito"),
            ("anual-8", "Revisión de seguridad: cerraduras, portón y luces exteriores", "Exterior"),
            ("anual-9", "Pintura o retoques menores", "Interior / exterior"),
            ("anual-10", "Limpieza profunda de colchones y tapizados", "Dormitorios / sala"),
            ("anual-11", "Revisión de electrodomésticos principales", "Cocina / lavadero"),
            ("anual-12", "Planificación de compras grandes o reparaciones", "General"),
        ],
    },
    {
        "id": "habitaciones",
        "title": "Por habitación",
        "frequency": "Control rápido de cierre",
        "description": "Control final para revisar que cada ambiente quede presentable al terminar la rutina.",
        "sort_order": 9,
        "tasks": [
            ("habitaciones-cocina-1", "Mesada limpia", "Cocina"),
            ("habitaciones-cocina-2", "Platos lavados", "Cocina"),
            ("habitaciones-cocina-3", "Cocina / hornallas sin grasa", "Cocina"),
            ("habitaciones-cocina-4", "Piso barrido", "Cocina"),
            ("habitaciones-cocina-5", "Basura retirada", "Cocina"),
            ("habitaciones-cocina-6", "Heladera ordenada", "Cocina"),
            ("habitaciones-cocina-7", "Alacena revisada", "Cocina"),
            ("habitaciones-cocina-8", "Trapos limpios", "Cocina"),
            ("habitaciones-bano-1", "Inodoro limpio", "Baño"),
            ("habitaciones-bano-2", "Lavamanos limpio", "Baño"),
            ("habitaciones-bano-3", "Espejo limpio", "Baño"),
            ("habitaciones-bano-4", "Ducha sin sarro visible", "Baño"),
            ("habitaciones-bano-5", "Toallas cambiadas", "Baño"),
            ("habitaciones-bano-6", "Papel higiénico repuesto", "Baño"),
            ("habitaciones-bano-7", "Piso trapeado", "Baño"),
            ("habitaciones-bano-8", "Basurero vacío", "Baño"),
            ("habitaciones-dormitorio-1", "Cama tendida", "Dormitorio"),
            ("habitaciones-dormitorio-2", "Ropa guardada", "Dormitorio"),
            ("habitaciones-dormitorio-3", "Piso limpio", "Dormitorio"),
            ("habitaciones-dormitorio-4", "Mesa de luz ordenada", "Dormitorio"),
            ("habitaciones-dormitorio-5", "Sábanas cambiadas", "Dormitorio"),
            ("habitaciones-dormitorio-6", "Placard ordenado", "Dormitorio"),
            ("habitaciones-dormitorio-7", "Ventilación diaria", "Dormitorio"),
            ("habitaciones-sala-1", "Mesa despejada", "Sala / comedor"),
            ("habitaciones-sala-2", "Sillones ordenados", "Sala / comedor"),
            ("habitaciones-sala-3", "Piso limpio", "Sala / comedor"),
            ("habitaciones-sala-4", "Controles y electrónicos ordenados", "Sala / comedor"),
            ("habitaciones-sala-5", "Polvo retirado", "Sala / comedor"),
            ("habitaciones-sala-6", "Ventanas limpias", "Sala / comedor"),
            ("habitaciones-sala-7", "Objetos fuera de lugar guardados", "Sala / comedor"),
            ("habitaciones-lavadero-1", "Ropa lavada", "Lavadero / patio"),
            ("habitaciones-lavadero-2", "Ropa doblada / guardada", "Lavadero / patio"),
            ("habitaciones-lavadero-3", "Productos ordenados", "Lavadero / patio"),
            ("habitaciones-lavadero-4", "Filtro de lavarropas revisado", "Lavadero / patio"),
            ("habitaciones-lavadero-5", "Piso limpio", "Lavadero / patio"),
            ("habitaciones-lavadero-6", "Basura retirada", "Lavadero / patio"),
            ("habitaciones-lavadero-7", "Herramientas guardadas", "Lavadero / patio"),
        ],
    },
]
